CHANGELOG.md, src/floo_axi_chimney.sv, src/floo_narrow_wide_chimney.sv
Added Chimney Parameters `EnMgrPort` and `EnSbrPort` to properly parametrize Manager resp. Subordinate-only instances of a chimney.
A couple of assertions were added to check that no packets arrive at a network interface that cannot be handled
=> Parametrize Manager/Subordinate-only chimneys

CHANGELOG.md, floogen/model/link.py, hw/floo_axi_chimney.sv, hw/floo_narrow_wide_chimney.sv, hw/floo_narrow_wide_pkg.sv, hw/tb/wave/tb_floo_axi_chimney.wave.tcl
- Wormhole routing for bursts was removed for some channels in the chimney since it is generally not necessary if the header information is sent in parallel to the payload.
- Write ordering in the narrow-wide version was incorrect. Sending `AW` and `W` beats over different channels would have allowed to arrive them out of order, if multiple managers are sending write requests to the same subordinate, which could result in interleaving of the data. This is now fixed by sending `AW` and `W` beats over the same wide channel. The `AW` and `W` beats are coupled together and wormhole routing prevents interleaving of the data.
=> chimney: Fix ordering of `AW` and `W` beats

.github/workflows/floogen.yml, CHANGELOG.md, floogen/floo_gen.py
CI: Removes the [verible formatter action](https://github.com/chipsalliance/verible-formatter-action/tree/main) with an annoying reviewdog bot that spams the pull requests. It was replaced in favor of the [install-verible action](https://github.com/chipsalliance/verible-actions-common/tree/main/install-verible)
floogen: Paths for the output directory are not relative to the current working directory.
=> floogen: Fix output directory + CI improvements

floogen/model/network.py, floogen/model/network_interface.py, floogen/model/router.py
pylint complained about deprecated functions from the `importlib` package.
=> floogen: Replace deprecated functions

CHANGELOG.md, floogen/model/network.py
The generation of the unique ID has been changed resp. aligned for 2D meshes to increment Y-first and X-second. This way the address range and ID increment are consistent with each other.
=> floogen: Align unique ID increments in 2D meshes

.gitlab-ci.yml, Makefile
`floogen` is not really needed for the RTL simulation as long as the auto-generated packages are up to date. The `floogen` prerequisite was therefore removed in the Makefile.
=> ci: Remove python requirements in internal GitLab CI

CHANGELOG.md, floogen/model/link.py, hw/floo_axi_pkg.sv, hw/floo_narrow_wide_pkg.sv
This was initially the case, but during refactoring got lost. This caused issues in the elaboration when a 32-bit type is used for `axi_ch_e`.
=> pkg: Use explicit bitwidth for enum values

CHANGELOG.md, Makefile, hw/floo_vc_arbiter.sv
Fixes a typedef in `floo_vc_arbiter` when setting `NumVirtChannels` to 1, that caused issue when compiling with Verilator.
=> hw: Minor fix for verilator compilation

CHANGELOG.md, hw/floo_axi_chimney.sv, hw/floo_meta_buffer.sv, hw/floo_narrow_wide_chimney.sv, hw/tb/tb_floo_narrow_wide_chimney.sv
This PR adds support for issuing non-atomic AXI transactions with multiple IDs downstream instead of serializing them by using a single constant ID as it is done now. This feature is mainly useful when the downstream AXI network itself has reordering capabilities, e.g., DDR controller. The cost is that the meta information needed to return responses has to be stored in an `id_queue` instead of a FIFO, which is known to have large complexity.
=> hw: Support downstream multi-ID in chimneys 

.github/workflows/floogen.yml, Bender.yml, CHANGELOG.md, README.md, docs/floogen.md, floogen/examples/axi_mesh_id.yml, floogen/examples/axi_mesh_src.yml, floogen/examples/axi_mesh_xy.yml, floogen/examples/occamy_mesh_src.yml, floogen/examples/occamy_mesh_xy.yml, floogen/examples/occamy_tree.yml, floogen/examples/single_cluster.yml, floogen/examples/terapool.yml, floogen/model/link.py, floogen/model/network.py, floogen/model/network_interface.py, floogen/model/protocol.py, floogen/model/router.py, floogen/templates/floo_axi_chimney.sv.mako, floogen/templates/floo_axi_router.sv.mako, hw/floo_axi_router.sv
Adds support for generating single-AXI networks with only the `req` and `rsp` channels. The configuration file now needs to have a `network_type` field, which determines whether a single-AXI network is generated (the options are `axi` or `narrow-wide`).
=> floogen: Add support for single-AXI networks

CHANGELOG.md, floogen/model/endpoint.py, floogen/model/graph.py, floogen/model/network.py, floogen/model/network_interface.py, floogen/model/router.py, floogen/model/routing.py, floogen/templates/floo_axi_chimney.sv.mako, floogen/templates/floo_axi_router.sv.mako, floogen/templates/floo_nw_chimney.sv.mako, floogen/templates/floo_nw_router.sv.mako
Before, the unique ID was restricted to the `SourceRouting` and `IdTable` routing algorithm, since it is actually required for routing. The `XYRouting` algorithm used XY coordinates instead.
However, FlooGen creates a SV enum of all endpoints, for which a unique ID is necessary independent of the routing algorithm.
Also fixes the alphanumeric ordering of the endpoints enum.
=> floogen: Use unique IDs for endpoints

CHANGELOG.md, floogen/examples/terapool.yml, floogen/model/endpoint.py, floogen/model/network.py, floogen/model/network_interface.py, floogen/model/routing.py
Can be used like this in the configuration file:
```yml
addr_range:
- start: 0x0000_0000
end: 0x7fff_ffff
- start: 0xC000_0000
end: 0xC000_ffff
```
=> floogen: Support endpoints with multiple non-contiguous address ranges

CHANGELOG.md, floogen/model/graph.py, floogen/model/network.py, floogen/model/network_interface.py, floogen/templates/floo_axi_chimney.sv.mako, floogen/templates/floo_nw_chimney.sv.mako, hw/tb/tb_floo_axi_mesh.sv, hw/tb/tb_floo_nw_mesh.sv
This PR changes names and fixes the ordering in the `ep_id_e` enum structure. Now endpoints that are created as 2D arrays are named as `EndpointX0Y1` instead of `Endpoint01`. Furthermore, this PR also fixes the issue where indexes with multiple digits where incorrectly ordered i.e. `EndpointX10Y0` coming before `EndpointX2Y0`
=> floogen: Fix endpoint enum ordering and names

hw/floo_pkg.sv
Assertions are not done at compile time. Therefore verilator throws an error
=> hw: Remove assertion in `axi_join_cfg` function

floogen/model/routing.py
Model validators in pydantic should only return `self` (see [here](https://docs.pydantic.dev/latest/concepts/validators/#using-the-decorator-pattern)). Fixes https://github.com/pulp-platform/FlooNoC/issues/92
=> floogen: Fix check for overlapping address ranges

CHANGELOG.md, floogen/templates/floo_axi_chimney.sv.mako, floogen/templates/floo_axi_router.sv.mako, floogen/templates/floo_nw_chimney.sv.mako, floogen/templates/floo_nw_router.sv.mako
Replaced concatenation in port connections for the `id_i` input with `localparam`.
=> floogen: Fixed synthesis issue with concatenation in port connections

hw/floo_meta_buffer.sv, hw/floo_route_select.sv
- Fixed unassigned signals in route_select;
- Added definition for $warning function to clean spyglass error
=> Fix unassigned signals to clean up spyglass

Bender.yml, CHANGELOG.md, Makefile, floogen/floo_gen.py, floogen/model/network.py, floogen/templates/floo_top_noc.sv.mako, floogen/templates/floo_top_noc_pkg.sv.mako, floogen/utils.py
For tile-based systems, the flattened FlooNoC top module is not necessar. This PR separates the package and the top-module into their own files. Furthermore `--only-pkg` and `--only-top` flags are added to omit the generation of one either of those files. Lastly, the output behaviour was changed. If `--outdir` resp. `-o` is not specified, the output will be printed to stdout.
=> floogen: Separate generated SV package and top-module

hw/floo_pkg.sv, hw/floo_route_select.sv, hw/floo_router.sv
1. Add support for YX-Routing
2. Add support for O1-Routing (XY/YX according to VC id)
3. Add support for Odd-Even-Routing
=> Merge Terapool-NoC adaptive routing supports

Bender.yml, CHANGELOG.md, Makefile, hw/floo_axi_chimney.sv, hw/floo_meta_buffer.sv, hw/floo_nw_chimney.sv, hw/floo_route_select.sv, hw/tb/tb_floo_axi_chimney.sv, hw/tb/tb_floo_nw_chimney.sv, hw/test/axi_aw_w_sync.sv
There is a deadlock potential if the downstream AXI network tries to sync the AW and W channel. This is sometimes necessary and also allowed by the AXI specifications (e.g. the [`axi_to_mem`](https://github.com/pulp-platform/axi/blob/master/src/axi_to_detailed_mem.sv) module needs address and data at the same time to generate a memory request). The problem with FlooNoC is that AW and W are sent over the same channels, which can causes a deadlock if the downstream AXI network waits for the W to be valid, which waits for the AW to be consumed.
This PR fixes this by buffering the AWs. Since corresponding AWs and W are guaranteed to be consecutive (due to ordering issues), a buffer of size 1 is already enough to solve this deadlock situation.
=> hw: Add AW cuts to chimneys
